1.0 Krakend
LLkaia/LaapY pull request #3
Opened 2024-01-04 12:57 UTC by AVK1206

Added endpoint into joing krakend.json

2024-01-04 13:10 UTC, LLkaia requested changes
1. Request must depend from name of specific laptop
2. app:8000 will not work because of absence in docker compose

2024-01-04 13:54 UTC, AVK1206 commented
Changed name of service from app to rating_app and changed port in krakend file
Added service in docker-compose file

2024-01-04 16:25 UTC, mehalyna approved these changes

2024-01-05 14:05 UTC, yurakomarnitskyi approved these changes

2024-01-05 16:48 UTC, LLkaia approved these changes

2024-01-05 16:49 UTC, merged